//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.31 at 07:16:33 PM PDT 
//


package com.tegik.facelectr.hearthbeat;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="foliofiscal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rfcreceptor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rfcemisor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="urltimbrado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "foliofiscal",
    "rfcreceptor",
    "rfcemisor",
    "urltimbrado"
})
@XmlRootElement(name = "SERTEG_INFOTIMBRADO")
public class SERTEGINFOTIMBRADO {

    @XmlElement(required = true)
    protected String foliofiscal;
    @XmlElement(required = true)
    protected String rfcreceptor;
    @XmlElement(required = true)
    protected String rfcemisor;
    @XmlElement(required = true)
    protected String urltimbrado;

    /**
     * Gets the value of the foliofiscal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFoliofiscal() {
        return foliofiscal;
    }

    /**
     * Sets the value of the foliofiscal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFoliofiscal(String value) {
        this.foliofiscal = value;
    }

    /**
     * Gets the value of the rfcreceptor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRfcreceptor() {
        return rfcreceptor;
    }

    /**
     * Sets the value of the rfcreceptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRfcreceptor(String value) {
        this.rfcreceptor = value;
    }

    /**
     * Gets the value of the rfcemisor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRfcemisor() {
        return rfcemisor;
    }

    /**
     * Sets the value of the rfcemisor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRfcemisor(String value) {
        this.rfcemisor = value;
    }

    /**
     * Gets the value of the urltimbrado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrltimbrado() {
        return urltimbrado;
    }

    /**
     * Sets the value of the urltimbrado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrltimbrado(String value) {
        this.urltimbrado = value;
    }

}
