//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.27 at 05:58:59 PM CDT 
//


package com.tegik.facelectr.servicios.sat.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ConsultaResult">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CodigoEstatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Estado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "consultaResult"
})
@XmlRootElement(name = "ConsultaResponse")
public class ConsultaResponse {

    @XmlElement(name = "ConsultaResult", required = true)
    protected ConsultaResponse.ConsultaResult consultaResult;

    /**
     * Gets the value of the consultaResult property.
     * 
     * @return
     *     possible object is
     *     {@link ConsultaResponse.ConsultaResult }
     *     
     */
    public ConsultaResponse.ConsultaResult getConsultaResult() {
        return consultaResult;
    }

    /**
     * Sets the value of the consultaResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsultaResponse.ConsultaResult }
     *     
     */
    public void setConsultaResult(ConsultaResponse.ConsultaResult value) {
        this.consultaResult = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CodigoEstatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Estado" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "codigoEstatus",
        "estado"
    })
    public static class ConsultaResult {

        @XmlElement(name = "CodigoEstatus", required = true, namespace="http://schemas.datacontract.org/2004/07/Sat.Cfdi.Negocio.ConsultaCfdi.Servicio")
        protected String codigoEstatus;
        @XmlElement(name = "Estado", required = true, namespace="http://schemas.datacontract.org/2004/07/Sat.Cfdi.Negocio.ConsultaCfdi.Servicio")
        protected String estado;

        /**
         * Gets the value of the codigoEstatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodigoEstatus() {
            return codigoEstatus;
        }

        /**
         * Sets the value of the codigoEstatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodigoEstatus(String value) {
            this.codigoEstatus = value;
        }

        /**
         * Gets the value of the estado property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEstado() {
            return estado;
        }

        /**
         * Sets the value of the estado property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEstado(String value) {
            this.estado = value;
        }

    }

}
