//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.27 at 04:03:07 PM CDT 
//



@javax.xml.bind.annotation.XmlSchema (
    elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
    xmlns = {
      @javax.xml.bind.annotation.XmlNs(prefix = "a",
                 namespaceURI="http://schemas.datacontract.org/2004/07/Sat.Cfdi.Negocio.ConsultaCfdi.Servicio") 
        }

    
    )

package com.tegik.facelectr.servicios.sat.response;

